export const ADD_GROCERY_ITEM = 'ADD_GROCERY_ITEM';
export const DELETE_GROCERY_ITEM = 'DELETE_GROCERY_ITEM';

export const GET_GROCERY_ITEMS = 'GET_GROCERY_ITEMS';
export const GET_GROCERY_ITEMS_SUCCESS = 'GET_GROCERY_ITEMS_SUCCESS';
export const GET_GROCERY_ITEMS_FAILURE = 'GET_GROCERY_ITEMS_FAILURE';
