export const ADD_GROCERY_ITEM = 'ADD_GROCERY_ITEM';
export const ADD_GROCERY_ITEM_SUCCEEDED = 'ADD_GROCERY_ITEM_SUCCEEDED';
export const ADD_GROCERY_ITEM_FAILURE = 'ADD_GROCERY_ITEM_FAILURE';

export const DELETE_GROCERY_ITEM = 'DELETE_GROCERY_ITEM';
export const DELETE_GROCERY_ITEM_SUCCEEDED = 'DELETE_GROCERY_ITEM_SUCCEEDED';
export const DELETE_GROCERY_ITEM_FAILURE = 'DELETE_GROCERY_ITEM_FAILURE';

export const GET_GROCERY_ITEMS = 'GET_GROCERY_ITEMS';
export const GET_GROCERY_ITEMS_SUCCESS = 'GET_GROCERY_ITEMS_SUCCESS';
export const GET_GROCERY_ITEMS_FAILURE = 'GET_GROCERY_ITEMS_FAILURE';

export const NEW_ITEM_UPDATE = 'NEW_ITEM_UPDATE';

export const BUY_UNBUY_GROCERY_ITEM = 'BUY_UNBUY_GROVERY_ITEM';
// export const BUY_GROCERY_ITEM_SUCCEEDED = 'BUY_GROVERY_ITEM_SUCCEEDED';
// export const BUY_GROCERY_ITEM_FAILURE = 'BUY_GROVERY_ITEM_FAILURE';

// export const UNBUY_GROCERY_ITEM = 'UNBUY_GROVERY_ITEM';
// export const UNBUY_GROCERY_ITEM_SUCCEEDED = 'UNBUY_GROVERY_ITEM_SUCCEEDED';
// export const UNBUY_GROCERY_ITEM_FAILURE = 'UNBUY_GROVERY_ITEM_FAILURE';

export const UPDATE_GORCERY_ITEM_SUCCEEDED = 'UPDATE_GORCERY_ITEM_SUCCEEDED';
export const UPDATE_GORCERY_ITEM_FAILURE = 'UPDATE_GORCERY_ITEM_FAILURE';
