export const ADD_GROCERY_ITEM = 'ADD_GROCERY_ITEM';
export const ADD_GROCERY_ITEM_SUCCEEDED = 'ADD_GROCERY_ITEM_SUCCEEDED';
export const ADD_GROCERY_ITEM_FAILURE = 'ADD_GROCERY_ITEM_FAILURE';

export const DELETE_GROCERY_ITEM = 'DELETE_GROCERY_ITEM';

export const GET_GROCERY_ITEMS = 'GET_GROCERY_ITEMS';
export const GET_GROCERY_ITEMS_SUCCESS = 'GET_GROCERY_ITEMS_SUCCESS';
export const GET_GROCERY_ITEMS_FAILURE = 'GET_GROCERY_ITEMS_FAILURE';

export const NEW_ITEM_UPDATE = 'NEW_ITEM_UPDATE';
